### ISSUE TITLE
CheckFunction is broken

### ISSUE THREAD

**Issue by gleblebedev** [xoofx/CppAst.CodeGen#22]
The function declaration has the following first argument:

function0(git_my_repo* myrepo

At the same time the generated code declares it as 

libnative.git_my_repo myrepo

which is incorrect. The structure is passed by pointer and should have ref or out in the c# declaration. It may work on some platforms as is (i.e. Windows) but may be broken on other (i.e. Linux).

**Comment by xoofx** [comment]
> which is incorrect. The structure is passed by pointer and should have ref or out in the c# declaration. It may work on some platforms as is (i.e. Windows) but may be broken on other (i.e. Linux).

Nope, that's not the way the generator is working. If it can detect that the `git_my_repo*` is always used as a pointer and it doesn't have any fields, then it will use an opaque pointer and convert `struct git_my_repo  { void* handle};` instead, which is much nicer.

**Comment by gleblebedev** [comment]
> `struct git_my_repo { void* handle};` instead, which is much nicer.
Ah, sorry, I've missed that part. Then the code is correct.

Do you have plans to continue the project? Do you accept PRs?
What is your plan to test generated code? Are you going to compile it and run, or maybe compile it an test IL bytecode, etc?

**Comment by xoofx** [comment]
> Do you have plans to continue the project? Do you accept PRs?
> What is your plan to test generated code? Are you going to compile it and run, or maybe compile it an test IL bytecode, etc?

I have extremely limited time for this project, so it's quite low priority, despite the fact that it requires lots of work to improve. I have been using https://github.com/xoofx/GitLib.NET as a playground, and there are some missing functionalities in order to make this project to be enough solid to support the various native/managed mapping problems.

So PR are always welcome, but depending on the amount of work in a PR, it might take a bit of time to review it.
